### ISSUE TITLE
How do I actually use this?

### ISSUE THREAD

**Issue by neverender24** [mokhosh/filament-kanban#6]
### What happened?

Hi thanks for this awesome free plugin, but I am wondring how to use this as this does not comes with a migration. So I was wondering how to get started and what table structures it needed.

### How to reproduce the bug

none

### Package Version

1

### PHP Version

8.2

### Laravel Version

10

**Comment by mokhosh** [comment]
This is designed to be flexible and ready to use with your own models.

In the simplest form, you need "status" and "title" columns on some model. Then you create a new kanban page for that model, and the generated class has comments for you to get started.

Please check out the readme and let me know if you have a more specific question.

**Comment by mkwsra** [comment]
I had some confusion as well, honestly, that's why I created this PL #7

**Comment by gmgarrison** [comment]
Found your plugin on the Filament plugins page and it's exactly what I need, but I don't have enough experience with Filament to be able to finish the implementation. I found this issue thread because I'm in the same place - I want a kanban style To Do board but I don't have an existing Model to use. I tried following your suggestions and made one and I got the board to appear, but there's no button to create a new model.

I wonder if it would be useful and easy to include an example Board that's already coded to match one of the example screenshots? Then developers could choose to either modify it (which might be easier than writing from scratch, especially if they aren't as experienced) or just delete it.

Just an idea - thanks for contributing to the open source community!!

**Comment by mokhosh** [comment]
@neverender24 @mkwsra @gmgarrison I'm creating some videos to help with this:

https://github.com/mokhosh/filament-kanban#video-tutorial

let me know what you think.
maybe I can improve the docs as well.

**Comment by vutasoftvn** [comment]
I have 2 panels including admin and user. How to create kanban on user panel?

**Comment by mokhosh** [comment]
@vutasoftvn have you watched the video tutorials?
https://github.com/mokhosh/filament-kanban#video-tutorial

**Comment by gmgarrison** [comment]
> @neverender24 @mkwsra @gmgarrison I'm creating some videos to help with this:
> 
> https://github.com/mokhosh/filament-kanban#video-tutorial
> 
> let me know what you think. maybe I can improve the docs as well.

Just wanted to let you know I've worked through the video series and they helped me get everything done that I wanted - thank you so much for producing them!!!

**Comment by mokhosh** [comment]
@gmgarrison that's great. thanks for letting me know.

**Comment by vutasoftvn** [comment]
> @vutasoftvn have you watched the video tutorials? https://github.com/mokhosh/filament-kanban#video-tutorial

![image](https://github.com/mokhosh/filament-kanban/assets/152179418/8c16f0be-3470-4443-8ebb-c807212be808)

How to customize icon for view? Thank you!
